foreground #e7eaed
background #1c252a
cursor #feffff
cursor_text_color #000000
selection_foreground #e7eaed
selection_background #4e6978

color0 #435a66
color1 #fb3841
color2 #5cf09e
color3 #fed032
color4 #00d3f2
color5 #fd7aa6
color6 #58ffd1
color7 #fffefe

color8 #a0b0b8
color9 #fc736d
color10 #acf6be
color11 #fee16c
color12 #6fcefe
color13 #fc669a
color14 #99ffe5
color15 #fffefe
background_opacity 0.85
